# Generated by Django 2.2.4 on 2020-06-25 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200625_1319'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_name', models.CharField(max_length=500)),
                ('appointment_date', models.CharField(max_length=50)),
                ('appointment_status', models.CharField(blank=True, choices=[('1', 'upcoming'), ('2', 'incipient'), ('3', 'completed'), ('4', 'cancelled')], max_length=1)),
                ('client_rate_appointment', models.CharField(blank=True, max_length=500)),
                ('clown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Clown')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestClientDetailss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_client_contacts', models.CharField(blank=True, max_length=500)),
                ('request_reason', models.CharField(blank=True, max_length=500)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Client')),
                ('clown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Clown')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAppointmentIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_issue', models.CharField(blank=True, max_length=500)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.Appointment')),
            ],
        ),
    ]
