# Generated by Django 2.2.4 on 2020-06-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200625_1319'),
        ('appointments', '0002_auto_20200625_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportappointmentissue',
            name='clown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Clown'),
        ),
        migrations.AlterField(
            model_name='requestclientdetailss',
            name='clown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Clown'),
        ),
    ]
