# Generated by Django 2.2.4 on 2020-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrate',
            name='rate',
            field=models.CharField(blank=True, choices=[('1', 'GOOD'), ('2', 'Alright'), ('3', 'Bad')], max_length=500),
        ),
    ]
